# The Docker image that will be used to build your app
image: 'stages:   - build   - test   - deploy  build_job:   stage:
  build   script:     - echo "Building the application..."     - mkdir
  build     - echo "Build complete" > build/status.txt  test_job:   stage:
  test   script:     - echo "Running tests..."  deploy_job:   stage:
  deploy   script:     - echo "Deploying to production..."   only:     - main'
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: h
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
